#!/bin/sh
default_sink_name=$(pactl get-default-sink)
default_sink_num=$(pactl list sinks | awk -v sink_name="$default_sink_name" '$1 == "Sink" { current_sink = $2 } $1 == "Name:" && $2 == sink_name { print current_sink; exit }')

function headphones_active() {
  local active_port=$(pactl list sinks | awk -v sink="$default_sink_num" '$1 == "Sink" { current_sink = $2 } $1 == "Active" && $2 == "Port:" && current_sink == sink { print $3; exit }')
  if [[ "$active_port" = "analog-output-headphones" ]]; then
    return 0
  fi
  return 1
}

headphones_active
headphones=$((1-$?))

function handle_event() {
  local event_change="Event 'change' on sink $default_sink_num"
  if ! [[ "$1" = "$event_change" ]]; then
    return
  fi
  if ! headphones_active; then
    if [[ $headphones -eq 1 ]]; then
      playerctl --all-players pause
    fi
    headphones=0
  else
    headphones=1
  fi
}

while read -r line; do
  handle_event "$line"
done < <(pactl subscribe)
